"""c-earchin finance-options proof artifacts stay executable.

The fixtures are generated by the released c-earchin v0.2.2 demo and
committed here so hello-chelis can validate the final stack without cloning
or building c-earchin from source.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
FIXTURES = REPO / "c-earchin" / "finance_options"


@pytest.fixture(scope="session", autouse=True)
def _chelis_on_path() -> None:
    if shutil.which("chelis") is None:
        pytest.skip("chelis not on PATH")


def test_c_earchin_finance_options_prove_passes() -> None:
    result = subprocess.run(
        [
            "chelis",
            "prove",
            str(FIXTURES / "options_rules.dp"),
            "--spans",
            str(FIXTURES / "options_rules.spans.json"),
            "--json",
        ],
        check=False,
        capture_output=True,
        text=True,
        cwd=REPO,
    )
    assert result.returncode == 0, result.stderr

    records = [json.loads(line) for line in result.stdout.splitlines() if line.strip()]
    summary = records[-1]
    assert summary == {
        "errors": 0,
        "failed": 0,
        "kind": "summary",
        "passed": 6,
        "total": 6,
        "unsupported": 0,
    }
    assert {record["name"] for record in records[:-1]} == {
        "req_FIN_001",
        "req_FIN_002",
        "req_FIN_003",
        "req_FIN_004",
        "req_FIN_005",
        "req_FIN_006",
    }


def test_c_earchin_finance_options_failure_maps_to_ears_line() -> None:
    result = subprocess.run(
        [
            "chelis",
            "prove",
            str(FIXTURES / "options_rules_fail.dp"),
            "--spans",
            str(FIXTURES / "options_rules.spans.json"),
        ],
        check=False,
        capture_output=True,
        text=True,
        cwd=REPO,
    )
    assert result.returncode != 0
    assert "property failure: req_FIN_003" in result.stdout
    assert "options_rules.ears:3:1 FIN-003" in result.stdout
    assert (
        "WHILE the exchange is open, the portfolio delta shall be at most the limit."
        in result.stdout
    )
