"""Surf and Deep are two surfaces over the same AST.

Every program in this repo ships both forms: the human-facing Surf
(`.ch`) and the canonical Deep s-expression form (`.dp`,
machine-generated by `chelis deep`). They exist together for
illustration — readers can compare the two surfaces side by side and
see the desugaring rules from `spec/02-surf-syntax.md` made concrete on
real programs.

Equivalence is enforced two ways for every `.ch` in src/, tests/,
and verify/:

1. **Drift** — the committed `.dp` is byte-identical to the output of
   `chelis deep <name>.ch`. This is the load-bearing guarantee: the
   two files cannot disagree about what the program means, because one
   is mechanically derived from the other and CI fails on any drift.

2. **Independent parse** — running `chelis check` on the `.ch` and
   `chelis check` on the `.dp` both succeed. The compiler accepts
   each surface independently; if we ever introduced a Surf form whose
   desugaring doesn't re-parse as Deep, this test fails.

The decompile direction (`chelis surf <name>.dp`) is best-effort and
not byte-stable today (e.g. list-literal sugar `[1, 2]` decompiles to
`Cons(1, Cons(2, Nil))`), so we don't assert round-trip identity in
that direction. The drift check makes the round-trip irrelevant: as
long as `.dp` is regenerated from `.ch`, the two surfaces always
represent the same program.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent


def discover() -> list[Path]:
    out: list[Path] = []
    for d in ("src", "tests", "verify"):
        out.extend(sorted((REPO / d).rglob("*.ch")))
    return out


@pytest.fixture(scope="session", autouse=True)
def _chelis_on_path() -> None:
    if shutil.which("chelis") is None:
        pytest.skip("chelis not on PATH")


@pytest.mark.parametrize("ch", discover(), ids=lambda p: str(p.relative_to(REPO)))
def test_committed_dp_matches_chelis_deep(ch: Path) -> None:
    """Drift: committed .dp must equal `chelis deep <name>.ch` exactly."""
    dp = ch.with_suffix(".dp")
    assert dp.exists(), f"missing sibling Deep file for {ch.relative_to(REPO)}"
    r = subprocess.run(
        ["chelis", "deep", str(ch)],
        check=False, capture_output=True, text=True, cwd=REPO,
    )
    assert r.returncode == 0, f"chelis deep {ch} failed:\n{r.stderr}"
    actual = dp.read_text()
    assert actual == r.stdout, (
        f"{dp.relative_to(REPO)} drifted from `chelis deep "
        f"{ch.relative_to(REPO)}`. Re-run `python3 scripts/regen_deep.py` "
        f"to bring them back into sync."
    )


@pytest.mark.parametrize("ch", discover(), ids=lambda p: str(p.relative_to(REPO)))
def test_both_surfaces_check_clean(ch: Path) -> None:
    """Both `.ch` and the matching `.dp` must `chelis check` clean.

    `chelis check` accepts either Surf or Deep input. For every
    program in the corpus, the front-end (parse + types + dimensions
    + effects + linearity) must produce no errors regardless of which
    surface is fed in.
    """
    dp = ch.with_suffix(".dp")
    for path in (ch, dp):
        r = subprocess.run(
            ["chelis", "check", str(path)],
            check=False, capture_output=True, text=True, cwd=REPO,
        )
        # `chelis check` emits a JSON fitness report. We accept rc=0
        # without parsing — any error makes it non-zero.
        assert r.returncode == 0, (
            f"chelis check {path.relative_to(REPO)} failed:\n"
            f"stdout: {r.stdout[:400]}\n"
            f"stderr: {r.stderr[:400]}"
        )
