"""Surf and Deep are two surfaces over the same AST.

Every program in this repo ships both forms: the human-facing Surf
(`.ch`) and the canonical Deep s-expression form (`.dp`,
machine-generated by `chelis deep`). They exist together for
illustration — readers can compare the two surfaces side by side and
see the desugaring rules from `spec/02-surf-syntax.md` made concrete on
real programs.

Equivalence is enforced by the **drift check**: the committed `.dp`
must be byte-identical to the output of `chelis deep <name>.ch`. CI
fails on any divergence; running `uv run scripts/regen_deep.py`
brings the two surfaces back into sync.

The drift check is the equivalence guarantee: by construction, the
`.dp` is whatever the compiler emits when desugaring the `.ch`, so the
two files cannot disagree about what the program means. There is no
separate "check both surfaces independently" test: `chelis check` on a
`.dp` checks it as a standalone program without loading the package,
so a sidecar that imports names reports them as unbound.

The decompile direction (`chelis surf <name>.dp`) is best-effort: list
literals decompile to Cons/Nil chains, `cast(x, f32)` to `(x as f32)`,
etc. The result is semantically equivalent but not byte-stable, so we
don't enforce round-trip identity. See `docs/surf_and_deep.md` for
the full design rationale.
"""

from __future__ import annotations

import importlib.util
import shutil
import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent

# Kept in lockstep with scripts/regen_deep.py by the assertion below.
WALK_DIRS = ("src", "tests", "tests_neg", "verify")


def discover() -> list[Path]:
    """Must stay in lockstep with `WALK_DIRS` in scripts/regen_deep.py: a
    directory the script regenerates but this check does not walk is a
    silent hole where a committed .dp can drift unnoticed.
    """
    out: list[Path] = []
    for d in WALK_DIRS:
        out.extend(sorted((REPO / d).rglob("*.ch")))
    return out


def test_walk_dirs_match_regen_script() -> None:
    """The generator and this checker must cover the same tree.

    When tests/negative/ moved to tests_neg/, updating only the script
    silently dropped three files from the drift check. Assert the two
    lists instead of trusting a comment.
    """
    spec = importlib.util.spec_from_file_location(
        "regen_deep", REPO / "scripts" / "regen_deep.py"
    )
    regen = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(regen)
    assert sorted(regen.WALK_DIRS) == sorted(WALK_DIRS)


@pytest.fixture(scope="session", autouse=True)
def _chelis_on_path() -> None:
    if shutil.which("chelis") is None:
        pytest.skip("chelis not on PATH")


@pytest.mark.parametrize("ch", discover(), ids=lambda p: str(p.relative_to(REPO)))
def test_committed_dp_matches_chelis_deep(ch: Path) -> None:
    """Drift: the committed .dp must equal `chelis deep <name>.ch` exactly.

    This is the equivalence assertion: the .dp is mechanically
    generated from the .ch, so any committed disagreement is a bug.
    """
    dp = ch.with_suffix(".dp")
    assert dp.exists(), f"missing sibling Deep file for {ch.relative_to(REPO)}"
    r = subprocess.run(
        ["chelis", "deep", str(ch)],
        check=False,
        capture_output=True,
        text=True,
        cwd=REPO,
    )
    assert r.returncode == 0, f"chelis deep {ch} failed:\n{r.stderr}"
    assert dp.read_text() == r.stdout, (
        f"{dp.relative_to(REPO)} drifted from `chelis deep "
        f"{ch.relative_to(REPO)}`. Re-run `uv run scripts/regen_deep.py` "
        f"to bring them back into sync."
    )
