services:
  hello-chelis:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      secrets:
        - github_token
    image: hello-chelis:0.8.0
    working_dir: /workspace
    volumes:
      - ..:/workspace
    stdin_open: true
    tty: true
    command: /bin/bash

secrets:
  github_token:
    environment: GITHUB_TOKEN
