services:
  hello-chelis:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: hello-chelis:0.7.0
    working_dir: /workspace
    volumes:
      - ..:/workspace
    stdin_open: true
    tty: true
    command: /bin/bash
