module Hello.Std.DatetimeCal
import Std.Datetime (Date, date, date_add_days, date_add_months, date_days_until, date_to_string, date_weekday, weekday_name, ClampToMonthEnd)
export (anniversary, date_weekday_name, days_until, format_date, after_30_days, week_before, new_years_day)
def anniversary(d: Date, years: i64) -> Date = date_add_months(d, mul(years, 12i64), ClampToMonthEnd)
def date_weekday_name(d: Date) -> string = weekday_name(date_weekday(d))
def days_until(from: Date, to: Date) -> i64 = date_days_until(from, to)
def format_date(d: Date) -> string = date_to_string(d)
def after_30_days(d: Date) -> Date = date_add_days(d, 30i64)
def week_before(d: Date) -> Date = date_add_days(d, -7i64)
def new_years_day(year: i64) -> Date = date(year, 1i64, 1i64)
