module Hello.Std.DatetimeCal
import Std.Time (Date, date, add_days, sub_days, days_between, date_to_string, day_of_week_name)
export (anniversary, weekday_name, days_until, format_date, after_30_days, week_before, new_years_day)
def anniversary(d: Date, years: i64) -> Date = add_days(d, mul(years, 365i64))
def weekday_name(d: Date) -> string = day_of_week_name(d)
def days_until(from: Date, to: Date) -> i64 = days_between(from, to)
def format_date(d: Date) -> string = date_to_string(d)
def after_30_days(d: Date) -> Date = add_days(d, 30i64)
def week_before(d: Date) -> Date = sub_days(d, 7i64)
def new_years_day(year: i64) -> Date = date(year, 1i64, 1i64)
