module Hello.Std.ReductionsLosses
import School.Loss.CrossEntropy (loss)
import School.Loss.Bce (bce_with_logits)
import School.Loss.KlDiv (kl_divergence)
import School.Loss.Metrics (perplexity)
import Std.Tensor.Reduce (prod)
export (sum_axis0, mean_axis0, prod_axis0, ce_loss, bce_loss, kl_loss, ce_perplexity)
def sum_axis0[r, c](x: &tensor[r, c, f32]) -> tensor[c, f32] = sum(x, cast(0, int32))
def mean_axis0(x: &tensor[3, 4, f32]) -> tensor[4, f32] = mean(x, cast(0, int32))
def prod_axis0[r, c](x: &tensor[r, c, f32]) -> tensor[c, f32] = prod(x, cast(0, int32))
def ce_loss[b, c](logits: tensor[b, c, f32], labels: tensor[b, c, f32]) -> tensor[b, f32] = loss(logits, labels)
def bce_loss[n](z: &tensor[n, f32], y: &tensor[n, f32]) -> tensor[n, f32] = bce_with_logits(z, y)
def kl_loss[n](p: tensor[n, f32], q: tensor[n, f32]) -> f32 = kl_divergence(p, q)
def ce_perplexity(scalar_loss: f32) -> f32 = perplexity(scalar_loss)
