name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  central:
    uses: Chelis-Lang/ci/.github/workflows/consumer.yml@5691ce4c7298cbccc4b3a579c909e916bff9a49b
    with:
      profile: container-ci
      chelis-version: 0.17.1
      chelis-linux-sha256: sha256:d3e6d057996622e3cc6bb1c063bc4d804c96553010b48ef42f98ef03328d078f
      coral-version: 0.7.32
      nautilus-version: 0.7.35
      school-version: 0.1.12
      domain-checks: true
    secrets:
      CHELIS_RELEASE_TOKEN: ${{ secrets.CHELIS_RELEASE_TOKEN }}
