name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  central:
    uses: Chelis-Lang/ci/.github/workflows/consumer-hello-chelis-lint.yml@1546f3d4f674c69c5bfd38621cc880d4d1b8fdf4
    secrets:
      CHELIS_RELEASE_TOKEN: ${{ secrets.CHELIS_RELEASE_TOKEN }}
