name: nightly

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

concurrency:
  group: nightly-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  central:
    uses: Chelis-Lang/ci/.github/workflows/consumer.yml@2beadace80ac926c6b5f8f8e5fc3645e3923310a
    with:
      profile: hello-chelis-nightly
      chelis-version: 0.14.0
      chelis-linux-sha256: sha256:0c790cfcc28ead0c283efb1bc1a1ddfabb6a46491212122aa283ef77f717e3ee
      coral-version: 0.7.30
      nautilus-version: 0.7.33
      school-version: 0.1.9
    secrets:
      CHELIS_RELEASE_TOKEN: ${{ secrets.CHELIS_RELEASE_TOKEN }}
