name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  central:
    uses: Chelis-Lang/ci/.github/workflows/consumer.yml@67a666fefe4bd056cdc628f28576d4ad6f43b943
    with:
      profile: hello-chelis-release
      chelis-version: 0.17.1
      chelis-linux-sha256: sha256:d3e6d057996622e3cc6bb1c063bc4d804c96553010b48ef42f98ef03328d078f
      package-version: 0.1.11
    secrets:
      CHELIS_RELEASE_TOKEN: ${{ secrets.CHELIS_RELEASE_TOKEN }}
